/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreaRestritaRouteImport } from './routes/area_restrita'

const AreaRestritaRoute = AreaRestritaRouteImport.update({
  id: '/area_restrita',
  path: '/area_restrita',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area_restrita': typeof AreaRestritaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area_restrita': typeof AreaRestritaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area_restrita': typeof AreaRestritaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/area_restrita'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/area_restrita'
  id: '__root__' | '/' | '/area_restrita'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaRestritaRoute: typeof AreaRestritaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area_restrita': {
      id: '/area_restrita'
      path: '/area_restrita'
      fullPath: '/area_restrita'
      preLoaderRoute: typeof AreaRestritaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaRestritaRoute: AreaRestritaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
